name: taskhub
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  google_sign_in: ^6.1.4
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  firebase_storage: ^11.2.5
  uuid: ^3.0.7
  shared_preferences: ^2.2.0

  #state management
  provider: ^6.0.5

  #service locator
  get_it: ^7.6.0

  #animation player or slider
  carousel_slider: ^4.2.1
  lottie: ^2.4.0

  # Opening phone setting
  app_settings: ^4.2.0

  #Notification
  flutter_local_notifications: ^14.1.1
  path_provider: ^2.0.15

  #internet request or internet connection checking
  http: ^1.0.0
  connectivity_plus: ^4.0.1

  #fonts
  google_fonts: ^5.0.0
  icons_plus: ^4.0.0

  #dialogs
  flutter_smart_dialog: ^4.9.2

  fl_country_code_picker: ^0.1.4
  pinput: ^2.2.31

  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  #for http calls
  dio: ^5.3.0

  #for navigations
  get: ^4.6.5
  shimmer: ^3.0.0
  local_image_provider: ^4.3.0
  external_path: ^1.0.3
  flutter_image_compress: ^2.0.4
  permission_handler:
  flutter_isolate: ^2.0.4
  easy_isolate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#EBF4F1"
  color_dark: "#010101"
  image: "assets/images/app_logo.png"
  android_gravity: center
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/lottie/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
